from pathlib import Path
from html import escape
import json
D=Path('dist');D.mkdir(exist_ok=True)
arrow='<img class="arrow" src="assets/arrow-up-right.svg" alt="" width="24" height="24">'
def btn(text,url='contact.html',outline=False):return f'<a class="button {"outline" if outline else ""}" href="{url}">{text}{arrow}</a>'
def media(label,w=1200,h=900):return f'<div class="media" style="--ratio:{w}/{h}" role="img" aria-label="Blank placeholder: {label}, {w} by {h} pixels"><span>{label}<small>{w} × {h} px</small></span></div>'
nav=[('about','Who we are'),('services','What we offer'),('insights','Insights'),('contact','Contact us')]
def header(page):return '<a class="skip" href="#main">Skip to content</a><header class="site-header"><div class="container header-inner"><a class="brand" href="index.html" aria-label="Geojit Private Wealth home"><img src="assets/logo.svg" width="166" height="64" alt="Geojit Private Wealth"><span>DIFC · Dubai</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="primary-nav">Menu <span aria-hidden="true">+</span></button><nav id="primary-nav" aria-label="Main navigation">'+''.join(f'<a href="{p}.html" {"aria-current=page" if p==page else ""}>{t}</a>' for p,t in nav)+btn('Start a conversation',outline=True)+'</nav></div></header>'
def footer():return '<footer><div class="container"><div class="footer-grid"><div><a href="index.html"><img src="assets/logo.svg" width="166" height="64" alt="Geojit Private Wealth"></a><p class="small">Geojit Private Wealth (DIFC) Limited</p><p class="small muted">N401, 4th Floor, Emirates Financial Towers<br>DIFC, Dubai, UAE</p></div><div><h2 class="footer-title">Explore</h2>'+''.join(f'<a href="{p}.html">{t}</a>' for p,t in nav)+'</div><div><h2 class="footer-title">Our solutions</h2>'+''.join(f'<a href="services.html#{s[0]}">{s[1]}</a>' for s in services)+'</div><div><h2 class="footer-title">Get in touch</h2><a href="tel:+97142850019">+971 4 285 0019</a><a href="mailto:corporate@geojitdifc.com">corporate@geojitdifc.com</a><a href="mailto:corporate@geojitdifc.com?subject=Legal%20and%20privacy%20documents">Request legal &amp; privacy documents</a></div></div><div class="footer-bottom"><span>© 2026 Geojit Private Wealth (DIFC) Limited</span><a href="#top">Back to top ↑</a></div></div></footer>'
def cta():return '<section class="cta"><div class="container cta-inner"><div><p class="eyebrow">Your next chapter</p><h2>Let’s start with<br>what matters to you.</h2></div><div><p>A conversation about your priorities.<br>A clearer perspective on your wealth.</p>'+btn('Start a conversation')+'</div></div></section>'
def hero(kicker,title,desc,visual=None):return '<section class="hero"><div class="container"><p class="eyebrow">'+kicker+'</p><h1>'+title+'</h1><p class="lead">'+desc+'</p>'+('</div><div class="container hero-media">'+visual if visual else '')+'</div></section>'
services=[('investment-products','Investment products','Access a broad investment universe.','Explore traditional and alternative asset classes in the context of your objectives, investment horizon and appetite for risk.',['Public market investments','Structured solutions & derivatives','Private equity investments','Cash management solutions','Life and non-life insurance']),('investment-management','Investment management','A disciplined approach to your portfolio.','Bring expert advice, research and a global perspective to investment decisions, with a portfolio approach aligned to your goals.',['Investment objectives','Portfolio alignment','Ongoing investment conversations']),('financing','Financing','Liquidity, with your long-term plan in view.','Explore financing needs alongside your investments, so near-term priorities can be considered within your wider wealth strategy.',['Liquidity requirements','Your investment horizon','Financing within your wealth strategy']),('legacy-planning','Legacy planning','Plan for the wealth you pass on.','Start a structured conversation about succession and the transition of wealth across generations, guided by your family’s priorities.',['Family priorities','Succession objectives','Intergenerational continuity'])]
articles=[('perspectives','24 September 2026','Earnings are king in 2026','Ankit Kapoor, CFA, FRM · Deputy Chief Investment Officer','earnings'),('press','24 June 2026','India’s Geojit Financials sees record busiest session on block deals','Press & media','block-deals')]
def articlecards():return ''.join('<article class="article-card" data-category="'+cat+'" data-title="'+escape(title.lower())+'">'+media('Editorial image',1200,750)+'<div class="article-body"><div class="meta"><span>'+('Wealth perspectives' if cat=='perspectives' else 'Press & media')+'</span><time>'+date+'</time></div><h3>'+title+'</h3><p class="small muted">'+author+'</p><button class="text-button" data-article="'+id+'">View details '+arrow+'</button></div></article>' for cat,date,title,author,id in articles)
home='<section class="home-hero container"><div class="home-copy"><p class="eyebrow">Geojit Private Wealth · DIFC</p><h1>Global perspective.<br>Personal purpose.</h1><p class="lead">Thoughtful wealth solutions for individuals, families and businesses with a world of possibilities ahead.</p>'+btn('Start a conversation')+'<a class="inline-link" href="services.html">Explore our solutions <span aria-hidden="true">↓</span></a></div>'+media('Hero image',1200,1400)+'</section><section class="section border-top"><div class="container"><div class="section-heading"><div><p class="eyebrow">The Geojit perspective</p><h2>See the bigger picture.<br>Stay close to your goals.</h2></div><p>Rooted in investment experience. Connected across markets. Focused on the wealth decisions that matter to you.</p></div><div class="value-grid">'+''.join(f'<article><span class="index">0{i+1}</span><h3>{a}</h3><p>{b}</p></article>' for i,(a,b) in enumerate([('Global perspective','Consider opportunities across markets, asset classes and geographies.'),('Independent thinking','Bring your priorities into focus with an open architecture approach.'),('Research-led decisions','Put market insights and disciplined thinking at the centre of your strategy.')]))+'</div><a class="inline-link" href="about.html">Get to know Geojit '+arrow+'</a></div></section><section class="section raised"><div class="container"><div class="section-heading"><div><p class="eyebrow">What we offer</p><h2>One wealth journey.<br>A wider set of possibilities.</h2></div><p>Four connected areas of expertise, shaped around your ambitions.</p></div><div class="solution-list">'+''.join(f'<a class="solution-row" href="services.html#{id}"><span class="index">0{i+1}</span><h3>{title}</h3><p>{tag}</p>{arrow}</a>' for i,(id,title,tag,desc,items) in enumerate(services))+'</div></div></section><section class="section"><div class="container"><div class="section-heading"><div><p class="eyebrow">Wealth perspectives</p><h2>Ideas for a wider view.</h2></div><a class="inline-link" href="insights.html">All insights '+arrow+'</a></div><div class="article-grid">'+articlecards()+'</div></div></section>'+cta()
about=hero('Who we are','A legacy built on trust.<br>A future shaped by perspective.','Investment experience, regional understanding and an international outlook.',media('About hero image',1600,640))+'<section class="section"><div class="container split"><div><p class="eyebrow">Our story</p><h2>Personal relationships.<br>Global possibilities.</h2></div><div class="prose"><p class="lead">Geojit Private Wealth (DIFC) Limited is an independent wealth management firm headquartered in the Dubai International Financial Centre.</p><p>We bring together Geojit’s investment heritage and the regional experience of Barjeel Geojit Financial Services LLC to serve internationally connected individuals, families and businesses.</p><p>Our approach starts with understanding your priorities, then bringing a wider perspective to the decisions ahead.</p></div></div></section><section class="heritage raised"><div class="container split"><div><p class="eyebrow">Where it began</p><div class="year">1987</div></div><div><h2>A foundation in Cochin.<br>An outlook beyond borders.</h2><p>M/s C J George and Co was established in Cochin, laying the foundation for Geojit’s investment services journey.</p></div></div></section><section class="section"><div class="container"><div class="section-heading"><div><p class="eyebrow">Our people</p><h2>Experience. Perspective.<br>A shared commitment.</h2></div><p>Meet our mentors, board and leadership.</p></div><div class="filter-bar" role="group" aria-label="Choose team group"><button class="chip" data-team="mentors" aria-pressed="true">Mentors</button><button class="chip" data-team="board" aria-pressed="false">Board of directors</button><button class="chip" data-team="leadership" aria-pressed="false">Leadership</button></div>'
teams={'mentors':[('Sheikh Sultan Saood Alqasimi','Chairman of the Board · Barjeel Geojit Financial Services'),('C J George','Founder & CMD · Geojit Financial Services Ltd')],'board':[('Jones George','Non-executive Director'),('Rahul Roy Choudhry','Non-executive Director'),('Hari Kumar Kodungalureth Sukumaran','Executive Director & SEO')],'leadership':[('Rakesh Kumar Agarwal','Head, Offshore and Investment Planning'),('Nidhi Kochar','Managing Partner'),('Ankit Kapoor','Deputy Chief Investment Officer'),('Anubha Tiwari','Manager, Operations and Service')]}
for key,people in teams.items():about+='<div class="team-grid" id="team-'+key+'" '+('hidden' if key!='mentors' else '')+'>'+''.join('<article>'+media('Portrait',600,750)+'<h3>'+n+'</h3><p class="small muted">'+r+'</p></article>' for n,r in people)+'</div>'
about+='</div></section>'+cta()
servicepage=hero('What we offer','Your ambitions.<br>A considered wealth strategy.','Explore connected solutions for investing, managing, financing and passing on your wealth.')+'<div class="subnav-wrap"><nav class="container subnav" aria-label="Solutions">'+''.join(f'<a href="#{s[0]}">{s[1]}</a>' for s in services)+'</nav></div>'
for i,(id,title,tag,desc,items) in enumerate(services):
 servicepage+='<section class="section service-section '+('raised' if i%2 else '')+'" id="'+id+'"><div class="container service-grid"><div><p class="eyebrow">0'+str(i+1)+' / '+title+'</p><h2>'+tag+'</h2><p>'+desc+'</p><details open><summary>'+('Explore investment categories' if i==0 else 'What we can discuss')+'</summary><ul class="plain-list">'+''.join('<li>'+x+'</li>' for x in items)+'</ul></details>'+btn('Discuss '+title.lower(),'contact.html?interest='+id,True)+'</div>'+media(title+' image')+'</div></section>'
servicepage+='<section class="section"><div class="container"><p class="eyebrow">How we begin</p><h2>A clear first step.</h2><div class="value-grid">'+''.join(f'<article><span class="index">0{i+1}</span><h3>{a}</h3><p>{b}</p></article>' for i,(a,b) in enumerate([('Understand','Share your priorities, circumstances and long-term goals.'),('Explore','Discuss the opportunities and considerations relevant to you.'),('Align','Agree the next steps for your wealth journey.')]))+'</div></div></section>'+cta()
insights=hero('Insights','A broader perspective.<br>A more informed conversation.','Explore investment thinking and the latest news from Geojit.')+'<section class="section compact-top"><div class="container"><div class="insights-toolbar"><div class="filter-bar" role="group" aria-label="Filter insights">'+''.join(f'<button class="chip" data-filter="{v}" aria-pressed="{str(i==0).lower()}">{l}</button>' for i,(v,l) in enumerate([('all','All insights'),('perspectives','Wealth perspectives'),('press','Press & media'),('events','Events')]))+'</div><div class="search-field"><label class="sr-only" for="search">Search insights</label><input type="search" id="search" placeholder="Search insights"></div></div><p id="result-count" class="small muted" aria-live="polite">2 insights</p><div class="article-grid">'+articlecards()+'</div><div id="empty-state" class="empty-state" hidden><h2>No insights found.</h2><p>Try another search or explore all insights.</p><button class="button outline" id="reset-search">Show all insights</button></div></div></section>'+cta()
contact=hero('Contact us','Every wealth journey<br>starts with a conversation.','Tell us what matters to you. We’ll help you explore the next step.')+'<section class="section compact-top"><div class="container contact-grid"><aside><p class="eyebrow">Our Dubai office</p><h2>Let’s connect.</h2><address>N401, 4th Floor<br>Emirates Financial Towers<br>DIFC, Dubai, UAE</address><div class="contact-links"><a href="tel:+97142850019">+971 4 285 0019</a><a href="mailto:corporate@geojitdifc.com">corporate@geojitdifc.com</a></div>'+media('Office / location image',1200,800)+'<a class="inline-link" href="https://www.google.com/maps/search/?api=1&amp;query=Emirates+Financial+Towers+DIFC+Dubai" target="_blank" rel="noopener">View location in Google Maps '+arrow+'<span class="sr-only"> (opens a new tab)</span></a></aside><div class="form-panel"><h2>How can we help?</h2><p class="small muted">Fields marked * are required.</p><form id="enquiry-form"><div class="form-grid"><div class="field"><label for="name">Full name *</label><input id="name" name="name" autocomplete="name" required maxlength="100"></div><div class="field"><label for="email">Email address *</label><input id="email" name="email" autocomplete="email" type="email" required maxlength="150"></div></div><div class="field"><label for="phone">Phone number <span>(optional)</span></label><input id="phone" name="phone" type="tel" autocomplete="tel" placeholder="Include your country code" maxlength="40"></div><div class="field"><label for="interest">I’d like to discuss *</label><select id="interest" name="interest" required><option value="">Select a topic</option>'+''.join(f'<option value="{s[0]}">{s[1]}</option>' for s in services)+'<option value="general">A general enquiry</option></select></div><div class="field"><label for="message">Tell us a little more <span>(optional)</span></label><textarea id="message" name="message" rows="5" maxlength="2000" placeholder="Share your priorities or a question. Please don’t include sensitive financial information."></textarea></div><label class="checkbox"><input type="checkbox" name="consent" required><span>I agree to be contacted by Geojit Private Wealth (DIFC) about this enquiry. *</span></label><p class="small muted">Your details stay in this page until you choose to open your email app. Nothing is sent automatically.</p><button class="button" type="submit">Prepare enquiry '+arrow+'</button><div id="email-draft" class="draft" hidden aria-live="polite"><h3>Your enquiry is ready to review.</h3><p>Open your email app, review the message and send when ready.</p><a class="button" id="email-link">Open email draft</a><button type="button" class="text-button" id="copy-enquiry">Copy enquiry</button><p id="copy-status" class="small" role="status"></p></div></form></div></div></section>'
from section_updates import update_sections
home,about=update_sections(home,about)
pages={'index':('Global perspective. Personal purpose.',home),'about':('Who we are',about),'services':('What we offer',servicepage),'insights':('Insights',insights),'contact':('Contact us',contact)}
for page,(title,body) in pages.items():
 html='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#000000"><meta name="description" content="Geojit Private Wealth DIFC. Thoughtful wealth solutions with a global perspective."><title>'+title+' | Geojit Private Wealth DIFC</title><link rel="stylesheet" href="assets/site.css"><script src="assets/site.js" defer></script></head><body id="top">'+header(page)+'<main id="main">'+body+'</main>'+footer()+'<dialog id="article-dialog" aria-labelledby="article-title"><button class="dialog-close" aria-label="Close article details">×</button><p class="eyebrow" id="article-category"></p><h2 id="article-title"></h2><p id="article-meta" class="muted"></p><p>The full article is available on request.</p><a class="button" id="request-article">Request article '+arrow+'</a></dialog></body></html>'
 (D/(page+'.html')).write_text(html)
(D/'assets/articles.json').write_text(json.dumps(articles))
